-- !Ups



CREATE TABLE "LISTS"(
	"ID" SERIAL PRIMARY KEY,
	"ID_USER" UUID REFERENCES "USERS"("ID") NOT NULL,
	"TASK" VARCHAR(55) NOT NULL,
	"STATUS" VARCHAR NOT NULL,
	"DESCRIPTION" TEXT,
	"IS_HIDDEN" BOOLEAN,
	"DUE" TIMESTAMP
);

-- !Downs
DROP TABLE "LISTS";
